import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { SiteHeader } from '@/components/site-header'
import { BlogFooter } from '@/components/footer'

const inter = Inter({ subsets: ['latin'], variable: '--font-mono' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='scroll-pt-[6rem]'>
      <body
        className={
          (cn('min-h-screen bg-background font-mono antialiased'),
          inter.variable)
        }
      >
        <div className='relative flex min-h-dvh flex-col bg-background px-4'>
          {/* fill everything */}
          <SiteHeader />
          <main className='flex-1'>{children}</main>
          <BlogFooter />
        </div>
      </body>
    </html>
  )
}
